exclude: ".git|.tox|.pytest_cache"
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.7.3"
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.13.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]
#  - repo: local
#    hooks:
#      - id: check-migrations
#        name: check-migrations
#        entry: poetry run python manage.py makemigrations --dry-run --check
#        types: [ python ]
#        pass_filenames: false
#        language: system
